name: NLP
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - jupyter
  - jupyterlab
  - ipykernel
  - ipywidgets
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - pip:
      - acl-anthology==0.5.3
      - adapters==1.2.0
      - aiofile==3.9.0
      - aiopath==0.7.7
      - antlr4-python3-runtime==4.9.3
      - anyio==4.10.0
      - app-paths==0.0.8
      - appdirs==1.4.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - asyncstdlib==3.13.1
      - attrs==24.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.5
      - bleach==6.2.0
      - caio==0.9.24
      - certifi==2025.8.3
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - citeproc-py==0.6.0
      - colorama==0.4.6
      - comm==0.2.3
      - debugpy==1.8.16
      - decorator==5.2.1
      - defusedxml==0.7.1
      - diskcache==5.6.3
      - docopt==0.6.2
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - fqdn==1.5.1
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.34.4
      - idna==3.10
      - ipython==9.5.0
      - ipython-pygments-lexers==1.1.1
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - langcodes==3.5.0
      - language-data==1.3.0
      - lark==1.2.2
      - lxml==5.3.2
      - marisa-trie==1.3.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.1.4
      - mpmath==1.3.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.5
      - notebook==7.4.5
      - notebook-shim==0.2.4
      - omegaconf==2.3.0
      - packaging==25.0
      - pandocfilters==1.5.1
      - parso==0.8.5
      - platformdirs==3.11.0
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.52
      - psutil==7.0.0
      - pure-eval==0.2.3
      - pycparser==2.23
      - pygments==2.19.2
      - pylatexenc==2.10
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.3.0
      - python-slugify==8.0.4
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==27.1.0
      - referencing==0.36.2
      - regex==2025.9.1
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.1.0
      - rnc2rng==2.7.0
      - rpds-py==0.27.1
      - rply==0.7.8
      - safetensors==0.6.2
      - send2trash==1.8.3
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - stack-data==0.6.3
      - stop-words==2018.7.23
      - strenum==0.4.15
      - sympy==1.14.0
      - terminado==0.18.1
      - texsoup==0.3.1
      - text-unidecode==1.3
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tokenizers==0.21.4
      - torch==2.8.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.51.3
      - types-python-dateutil==2.9.0.20250822
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - unidecode==1.4.0
      - unpackable==0.0.4
      - uri-template==1.3.0
      - urllib3==2.5.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.14
